chat-format: "<player>: <message>"
mentions: true

messages: # replace with null to disable
  join: "<player> <yellow>joined the game"
  quit: "<player> <yellow>left the game"
  sleep: "<player> <yellow>went to sleep"

# remove this section to disable emojis
emojis:
  "<3": "<red>❤"
  ":yes:": "<green>✔"
  ":no:": "<red>✖"
  ":skull:": "<white>☠"
  ":shrug:": "<yellow>¯\\_(ツ)_/¯"
  ":tableflip:": "<red>(╯°□°）╯<gray>︵ ┻━┻"
  "o/": "<light_purple>( ﾟ◡ﾟ)/"
  ":snail:": "<yellow>@<green>'<yellow>-<green>'"
  ":gimme:": "<aqua>༼つ◕_◕༽つ"
  "h/": "<yellow>ヽ(^◇^*)/"
  ":cute:": "<yellow>(<green>✿<yellow>◠‿◠)"
  ":lol:": "<red><bold>LOL"
  ":oof:": "<red><bold>OOF"
  ":ugh:": "<yellow>¬_¬"